#Read csv file
aq <- read.csv("KesaAQ.csv", header = TRUE, sep = ";", stringsAsFactors = FALSE, strip.white = TRUE)
#Ensure Date column is of type Date
aq$Date <- as.Date(aq$Date, "%d/%m/%Y")
#Split out AQs by round and date
aqround1 <- subset(aq, aq$Round == 1 && aq$Date == "yyy-mm-dd")
aqround2 <- subset(aq, aq$Round == 2 && aq$Date == "yyy-mm-dd")
aqround3 <- subset(aq, aq$Round == 3 && aq$Date == "yyy-mm-dd")
aqround4 <- subset(aq, aq$Round == 4 && aq$Date == "yyy-mm-dd")
aqround5 <- subset(aq, aq$Round == 5 && aq$Date == "yyy-mm-dd")
#Split out Rounds by BG
##Round 1
aqR1BG1 <- subset(aqround1, aqround1$BG == 1)
aqR1BG2 <- subset(aqround1, aqround1$BG == 2)
aqR1BG3 <- subset(aqround1, aqround1$BG == 3)
##Round 2
aqR2BG1 <- subset(aqround2, aqround2$BG == 1)
aqR2BG2 <- subset(aqround2, aqround2$BG == 2)
aqR2BG3 <- subset(aqround2, aqround2$BG == 3)
##Round 3
aqR3BG1 <- subset(aqround3, aqround3$BG == 1)
aqR3BG2 <- subset(aqround3, aqround3$BG == 2)
aqR3BG3 <- subset(aqround3, aqround3$BG == 3)
##Round 4
aqR4BG1 <- subset(aqround4, aqround4$BG == 1)
aqR4BG2 <- subset(aqround4, aqround4$BG == 2)
aqR4BG3 <- subset(aqround4, aqround4$BG == 3)
##Round 5
aqR5BG1 <- subset(aqround5, aqround5$BG == 1)
aqR5BG2 <- subset(aqround5, aqround5$BG == 2)
aqR5BG3 <- subset(aqround5, aqround5$BG == 3)
#Create dataframe for each player
jachal <- subset(aq, aq$Player == "The_Jachal")
jct <- subset(aq, aq$Player == "jct22")
Mouadh <- subset(aq, aq$Player == "Mouadh05")
blaize <- subset(aq, aq$Player == "Blaizemeister")
logan <- subset(aq, aq$Player == "LoganManoj")
sadud <- subset(aq, aq$Player == "sadud")
royalc <- subset(aq, aq$Player == "RoyalC")
abdallah <- subset(aq, aq$Player == "Abdallah222")
denise <- subset(aq, aq$Player == "Denise1")
czako <- subset(aq, aq$Player == "Czakobmx")
chill <- subset(aq, aq$Player == "Chillingss")
msssa <- subset(aq, aq$Player == "The MsssA")
sarel <- subset(aq, aq$Player == "Sarelo")
cr <- subset(aq, aq$Player == "Caesar Royale")
helanie <- subset(aq, aq$Player == "helanie23")
jan <- subset(aq, aq$Player == "Jannel1984")
chris <- subset(aq, aq$Player == "Chrisslabbert20")
fu <- subset(aq, aq$Player == "123Fu2")
shabz <- subset(aq, aq$Player == "Lord Shabz")
viver <- subset(aq, aq$Player == "viver21")
mumble <- subset(aq, aq$Player == "mumblebumble")
ma <- subset(aq, aq$Player == "M-Adel")
blood <- subset(aq, aq$Player == "Blood Bullet")
akash <- subset(aq, aq$Player == "akash_512")
worm <- subset(aq, aq$Player == "worm1112")
galax <- subset(aq, aq$Player == "league of galax")
mud <- subset(aq, aq$Player == "Mud ex")
tiny <- subset(aq, aq$Player == "Tiny3001")
